name: integration

on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  dim:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          - toxenv: py310-dim
          - toxenv: py311-dim
          - toxenv: py312-dim
          - toxenv: py313-dim

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/proxystore/proxystore-dim:nightly
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Pull image and run tests
        run: tox -e ${{ matrix.toxenv }}
